#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"
#include "group0.h"

#include "bubble/geo.inc.c"
#include "walk_smoke/geo.inc.c"
#include "burn_smoke/geo.inc.c"
#include "small_water_splash/geo.inc.c"
#include "water_wave/geo.inc.c"
#include "sparkle/geo.inc.c"
#include "water_splash/geo.inc.c"
#include "sparkle_animation/geo.inc.c"
#include "mario/geo.inc.c"

#include "cheese_follow/geo.inc.c"
#include "wisp1/geo.inc.c"
//#include "wisp2/geo.inc.c"
#include "mario_riders/geo.inc.c"
#include "mario_winter/geo.inc.c"
#include "mario_spring/geo.inc.c"
#include "mario_unicorn/geo.inc.c"
#include "mario_yukata/geo.inc.c"
#include "mario_swimsuit/geo.inc.c"
#include "mario_halloween/geo.inc.c"
#include "mario_detective/geo.inc.c"
#include "mario_drummer/geo.inc.c"
#include "mario_princess/geo.inc.c"
#include "mario_mario/geo.inc.c"
#include "mario_lunar/geo.inc.c"