extern const GeoLayout cotmc_area_2_geo[];
extern const GeoLayout cotmc_area_2[];
extern const Collision cotmc_area_2_collision[];
extern const MacroObject cotmc_area_2_macro_objs[];
extern Lights1 cotmc_dl_sm64_material_lights;
extern Lights1 cotmc_dl_walls_lights;
extern Lights1 cotmc_dl_lakebed_lights;
extern Lights1 cotmc_dl_water_lights;
extern u8 cotmc_dl_cave_walls_i8[];
extern u8 cotmc_dl_lakebed_ci4[];
extern u8 cotmc_dl_lakebed_ci4_pal_rgba16[];
extern u8 cotmc_dl_water_ci8[];
extern u8 cotmc_dl_water_ci8_pal_rgba16[];
extern Vtx cotmc_dl_Cube_mesh_vtx_0[24];
extern Gfx cotmc_dl_Cube_mesh_tri_0[];
extern Vtx cotmc_dl_Level_mesh_layer_1_vtx_0[213];
extern Gfx cotmc_dl_Level_mesh_layer_1_tri_0[];
extern Vtx cotmc_dl_Level_mesh_layer_1_vtx_1[21];
extern Gfx cotmc_dl_Level_mesh_layer_1_tri_1[];
extern Vtx cotmc_dl_Water_mesh_layer_5_vtx_0[23];
extern Gfx cotmc_dl_Water_mesh_layer_5_tri_0[];
extern Gfx mat_cotmc_dl_sm64_material[];
extern Gfx mat_cotmc_dl_walls[];
extern Gfx mat_revert_cotmc_dl_walls[];
extern Gfx mat_cotmc_dl_lakebed[];
extern Gfx mat_revert_cotmc_dl_lakebed[];
extern Gfx mat_cotmc_dl_water[];
extern Gfx mat_revert_cotmc_dl_water[];
extern Gfx cotmc_dl_Cube_mesh[];
extern Gfx cotmc_dl_Level_mesh_layer_1[];
extern Gfx cotmc_dl_Water_mesh_layer_5[];
extern Gfx cotmc_dl_material_revert_render_settings[];
